spring.application.name=auth-service

spring.datasource.url=jdbc:postgresql://localhost:5432/emphathai_db
spring.datasource.username=postgres
spring.datasource.password=Postgres@2004
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

jwt.secret=emphathai-super-secret-key-2024-make-this-very-long
jwt.expiration=3600000

server.port=8080